server:
  port: 8080

spring:
  application:
    name: ms-persona-cliente

  webflux:
    base-path: /api/v1

  # --- Base de Datos (PostgreSQL) ---
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank_db}
    username: ${SPRING_DATASOURCE_USERNAME:user_bank}
    password: ${SPRING_DATASOURCE_PASSWORD:password_bank}
    driver-class-name: org.postgresql.Driver

  # --- Configuracion de JPA / Hibernate ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # --- Conexion a RabbitMQ
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      path: /swagger-ui.html